### ISSUE TITLE
Failed to install matplotlib-0.6.0 in Ubuntu 16.04

### ISSUE THREAD

**Issue by vincent-hui** [abarbu/matplotlib-haskell#8] opened 2018-12-18 06:25 UTC
Failed to install matplotlib-0.6.0 in Ubuntu 16.04 after running "cabal install matplotlib"
```
vincent@vincent-VirtualBox:~$ cabal install matplotlib
Resolving dependencies...
Configuring matplotlib-0.6.0...
Building matplotlib-0.6.0...
Failed to install matplotlib-0.6.0
Build log ( /home/vincent/.cabal/logs/ghc-8.4.3/matplotlib-0.6.0-4BQrEUftjjoBFPSHtAVHgo.log ):
cabal: Entering directory '/tmp/cabal-tmp-6081/matplotlib-0.6.0'
Configuring matplotlib-0.6.0...
Preprocessing library for matplotlib-0.6.0..
Building library for matplotlib-0.6.0..
[1 of 2] Compiling Graphics.Matplotlib.Internal ( src/Graphics/Matplotlib/Internal.hs, dist/build/Graphics/Matplotlib/Internal.o )

src/Graphics/Matplotlib/Internal.hs:36:10: error:
    • No instance for (Semigroup Matplotlib)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Matplotlib’
   |
36 | instance Monoid Matplotlib where
   |          ^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-6081/matplotlib-0.6.0'
cabal: Error: some packages failed to install:
matplotlib-0.6.0-4BQrEUftjjoBFPSHtAVHgo failed during the building phase. The
exception was:
ExitFailure 1
```
How to solve this issue??
Thank a lot.

**Comment by hgiasac** [comment] 2019-01-09 17:23
This bug is caused by GHC 8.4 breaking changes. It was fixed in master branch already. However, this patch hasn't been published on hackage yet. 
You can revert back to GHC 8.2, or build from source while waiting for @abarbu

**Comment by abarbu** [comment] 2019-03-17 23:22
Hi folks, sorry for the delay. The latest version fixes this problem. Let me know if you have any other issues.

**Closed as completed by abarbu** 2019-03-17 23:22 UTC
